### ISSUE TITLE
alarm fails

### ISSUE THREAD

**Issue by dalb8** [theScrabi/Terminightor#10]
I choose both default alarm sound and non-default (with storage permission granted), yet when the hour arrives the alarm doesn't go off. Stock lg g4 android 6

**Comment by dalb8** [comment]
0.9.7 from fdroid.org

**Comment by theScrabi** [comment]
Let me guess, you are german, and yesterday it was DST swap right?

O happy day (:

However it should be fine by tomorrow ... I should just try to fix this until next year :)

**Comment by theScrabi** [comment]
But it's goof this happens now...

**Comment by theScrabi** [comment]
All right It should be fixed with version [1.0.0](https://github.com/theScrabi/Terminightor/releases/tag/v1.0.0)

**Comment by dalb8** [comment]
Sure enough.
