### ISSUE TITLE
Option for silencing alarm with *any* NFC tag

### ISSUE THREAD

**Issue by schubidoo** [theScrabi/Terminightor#5]
Hi -
This is a really cool App!
I have a feature suggestion: Could you add a function to the NFC tag registratio that an alarm can be set such that it can be silenced by _any_ NFC tag? That way, one could even use those tags which change their ID all the time. The impact of the alarm would not be less than in the normal mode as long as you can assure that there are no tags next to your bed (which should be easy enough for most people). 

Advantage: you don't need to have a special tag, just use one of NFC cards you have in your wallet anyway (those are usually of the ID changing style).
Place the wallet in the kitchen/bath/wherever, voila.

Great work at any case!

**Comment by theScrabi** [comment]
I already use those in my wallet xD
I could add an option to the settings menu, that will disable testing the ID.

**Comment by schubidoo** [comment]
Interesting - I just checked, but all the tags in my wallet are the type which randomizes their IDs. Which in principle is good, of course.

Yes, what you say would work.
I was thinking slightly different, and even easier, along the lines of a second ("any Tag") button next to the red "register NFC" button in the lower ight corner of the alarm configuration. You would use the "register NFC" button for a specific NFC tag, and the new button for "any tag" functionality. When using that button, then instead of the number code like "5,-6,7,8" it would just say "any Tag" for that alarm, and that's it.

Thanks for considering!

**Comment by theScrabi** [comment]
Thats not making it easier xD. That would make it worse since, I had to think about a new layout, and the SQL had to be changed. Adding a small check to the Settings is almost a one liner, and therefore its more likely I can do it soon.

**Comment by theScrabi** [comment]
Ok I added an option just as I said. Should be available in the next few days.
