### ISSUE TITLE
"Repeat" set even though repeat box was never touched

### ISSUE THREAD

**Issue by schubidoo** [theScrabi/Terminightor#6]
How to reproduce:
Add new alarm
Set time
Add Tag
(Do not set repeat, leave box unchecked)
Leave Dialog

Open the newly created alarm again

Outcome:
Now the alarm is mysteriously set to repeat on all days except Sat and Sun. 

Expected outcome:
It should still be without repeat, of course.

**Comment by theScrabi** [comment]
Aha, confirmed.

**Comment by theScrabi** [comment]
Ok should be fixed with 0.9.5.
Version is rolled out. Should be available on f-droid the next few days.
